version: '3.8'

services:
  app:
    container_name: application_con
    image: thanhlam2k4/nodejs_app:latest
    ports:
      - 3000:3000
    depends_on:
      - mysql_server
    restart: always

  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=thanhlam
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
