version: '3.8'

services:
  app:
    container_name: application_con
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=thanhlam
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data_dev:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped

volumes:
  mysql_data_dev:
