version: '3.8'

services:
  app:
    container_name: application_con
    image: a52447879/nodejs_app:latest
    ports:
      - '3000:3000'
    depends_on:
      mysql_server:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql_server
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=thanhlam
      - MYSQL_PASSWORD=secret
    restart: always

  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=thanhlam
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
      # 초기화 SQL 스크립트
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  mysql_data:
    driver: local
